{{- if .Values.frontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sentinel-iac.fullname" . }}-frontend
  labels:
    app.kubernetes.io/name: {{ include "sentinel-iac.name" . }}-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sentinel-iac.name" . }}-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "sentinel-iac.name" . }}-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.port }}
              name: http
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.port }}
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.port }}
            initialDelaySeconds: 5
            periodSeconds: 15
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
      terminationGracePeriodSeconds: 30
{{- end }}
