apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sentinel-iac.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "sentinel-iac.name" . }}
    helm.sh/chart: {{ include "sentinel-iac.chart" . }}
