apiVersion: v1
kind: Service
metadata:
  name: {{ include "sentinel-iac.fullname" . }}-postgresql
spec:
  selector:
    app.kubernetes.io/name: {{ include "sentinel-iac.name" . }}-postgresql
  ports:
    - port: {{ .Values.postgresql.port }}
      targetPort: {{ .Values.postgresql.port }}
---
{{- if .Values.api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sentinel-iac.fullname" . }}-api
  labels:
    app.kubernetes.io/name: {{ include "sentinel-iac.name" . }}-api
spec:
  selector:
    app.kubernetes.io/name: {{ include "sentinel-iac.name" . }}-api
  ports:
    - port: {{ .Values.api.port }}
      targetPort: {{ .Values.api.port }}
---
{{- end }}
{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sentinel-iac.fullname" . }}-frontend
  labels:
    app.kubernetes.io/name: {{ include "sentinel-iac.name" . }}-frontend
spec:
  selector:
    app.kubernetes.io/name: {{ include "sentinel-iac.name" . }}-frontend
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
{{- end }}
